services:
  - type: web
    name: hotspringwebapp           # any name is fine
    plan: free

    dockerfilePath: ./Dockerfile    # use the Dockerfile you created
    autoDeploy: true

    # 👇 tells Render which container port to route — disables port-scanner
    port: 10000

    healthCheckPath: /health        # we already added this endpoint
