services:
  - type: web
    name: hotspringwebapp
    plan: free
    dockerfilePath: ./Dockerfile

    # tell Render exactly which port in the container to expose
    ports:
      - port: 10000         # ← matches EXPOSE and Gunicorn
        protocol: tcp

    healthCheckPath: /health
