services:
  - type: web
    name: hotspringwebapp
    env: docker
    plan: free
    autoDeploy: true

    # Optional: Timeout settings for long loads
    healthCheckPath: /
    dockerfilePath: ./Dockerfile

    envVars:
      - key: PORT
        value: 10000

